<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPublicSetter(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPublicSetter(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPublic(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPublic(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsProtectedSetter(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsProtectedSetter(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsProtectedGetter(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsProtectedGetter(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsProtected(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsProtected(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPrivateSetter(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPrivateSetter(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPrivateGetter(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPrivateGetter(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPrivate(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsPrivate(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsInternalSetter(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsInternalSetter(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsInternal(System.Data.Metadata.Edm.NavigationProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="PJonDevelopment.CodeGenerator.EdmExtensions.#IsInternal(System.Data.Metadata.Edm.EdmProperty)", Justification:="Method created for simetry.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="PJonDevelopment.CodeGenerator", Justification:="The namespace is by design.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId:="System.Data.Entity.Design, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", Justification:="It's not possible to determine version 3.5 SP1")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId:="System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", Justification:="It's not possible to determine version 3.5 SP1")> 
